export { default } from 'next-auth/middleware';

export const config = {
  matcher: [
    '/dashboard/:path*',
    '/facturacion/:path*',
    '/ventas/:path*',
    '/compras/:path*',
    '/inventario/:path*',
    '/tesoreria/:path*',
    '/configuracion/:path*',
    '/admin/:path*',
    '/pos/:path*',
    '/clientes/:path*',
    '/facturas/:path*',
    '/recibos/:path*',
    '/presupuestos/:path*',
    '/tickets/:path*',
    '/cuentas-corrientes/:path*',
    '/listas-precios/:path*',
    '/proveedores/:path*',
    '/reportes/:path*',
    '/libro-iva/:path*',
    '/transacciones/:path*',
    '/vendedores/:path*',
    '/contador-ia/:path*',
    '/api/branches/:path*',
    '/api/warehouses/:path*',
    '/api/inventory/migrate-stock',
    '/api/dashboard/:path*',
    '/api/admin/:path*',
  ],
};
